openapi: 3.0.0
info:
  title: Notification And Alert API
  version: 1.0.0
paths:
  /create-team:
    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeamRequest'
      responses:
        '200':
          description: Team created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamResponse'
        '404':
          description: Team not found

  /invite-team:
    post:
      summary: Invite a user to a team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteTeamRequest'
      responses:
        '200':
          description: User invited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InviteTeamResponse'
        '404':
          description: Team not found

  /update-notification:
    post:
      summary: Update notification settings for a user in a team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNotificationRequest'
      responses:
        '200':
          description: Notification settings updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateNotificationResponse'
        '404':
          description: Team not found

  /change-team:
    post:
      summary: Change a user's team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeTeamRequest'
      responses:
        '200':
          description: User's team changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangeTeamResponse'
        '404':
          description: Team not found

  /verify-email-within-team:
    post:
      summary: Verify if a user's email is subscribed to a team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
      responses:
        '200':
          description: Verification successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyEmailResponse'
        '404':
          description: Team not found

  /send-notification:
    post:
      summary: Send a notification to team subscribers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendNotificationRequest'
      responses:
        '200':
          description: Notification sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
        '404':
          description: Team not found

components:
  schemas:
    CreateTeamRequest:
      type: object
      properties:
        Team_Name:
          type: string
      required:
        - Team_Name

    TeamResponse:
      type: object
      properties:
        Topic_ARN:
          type: string
        Message:
          type: string

    InviteTeamRequest:
      type: object
      properties:
        TeamName:
          type: string
        UserEmail:
          type: string
      required:
        - TeamName
        - UserEmail

    InviteTeamResponse:
      type: object
      properties:
        Message:
          type: string

    UpdateNotificationRequest:
      type: object
      properties:
        Team_Name:
          type: string
        User_Email:
          type: string
        Filter_List:
          type: object
          additionalProperties:
            type: string

    UpdateNotificationResponse:
      type: object
      properties:
        Message:
          type: string

    ChangeTeamRequest:
      type: object
      properties:
        OldTeamName:
          type: string
        UserEmail:
          type: string
        NewTeamName:
          type: string
      required:
        - OldTeamName
        - UserEmail
        - NewTeamName

    ChangeTeamResponse:
      type: object
      properties:
        Message:
          type: string

    VerifyEmailRequest:
      type: object
      properties:
        TeamName:
          type: string
        UserEmail:
          type: string
      required:
        - TeamName
        - UserEmail

    VerifyEmailResponse:
      type: object
      properties:
        IsSubscribed:
          type: string
        IsConfirmed:
          type: string

    SendNotificationRequest:
      type: object
      properties:
        TeamName:
          type: string
        FilterName:
          type: string
        EmailTopic:
          type: string
        Message:
          type: string
      required:
        - TeamName
        - FilterName
        - EmailTopic
        - Message

    NotificationResponse:
      type: object
      properties:
        Message:
          type: string
